name: bci-eeg

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - mne
  - jupyterlab
  - ipykernel
  - setuptools<81
  - pip
  - pip:
      - brainflow==5.22.2
